---@diagnostic disable: undefined-global
-- NONE OF THESE EVENTS ARE UPDATED. DO NOT LISTEN FOR THIS EVENTS THIS IS FROM OLD API
AddEventHandler("vorpCore:subWeapon", INVENTORY_API.MAIN.REMOVE_WEAPON)
AddEventHandler("vorpCore:giveWeapon", INVENTORY_API.MAIN.GIVE_WEAPON)
AddEventHandler("vorpCore:registerWeapon", INVENTORY_API.MAIN.ADD_WEAPON)
AddEventHandler("vorpCore:addItem", INVENTORY_API.MAIN.ADD_ITEM)
AddEventHandler("vorpCore:subItem", INVENTORY_API.MAIN.SUB_ITEM)
AddEventHandler("vorpCore:setItemMetadata", INVENTORY_API.MAIN.SET_ITEM_METADATA)
AddEventHandler("vorpCore:subItemID", INVENTORY_API.MAIN.SUB_ITEM_BY_ID)
AddEventHandler("vorpCore:getItem", INVENTORY_API.MAIN.GET_ITEM)
AddEventHandler("vorpCore:getItemByMainId", INVENTORY_API.MAIN.GET_ITEM_BY_ID)
AddEventHandler("vorpCore:getItemByName", INVENTORY_API.MAIN.GET_ITEM_BY_NAME)
AddEventHandler("vorpCore:getcomps", INVENTORY_API.MAIN.GET_WEAPON_COMPONENTS)
AddEventHandler("vorpCore:deletegun", INVENTORY_API.MAIN.DELETE_WEAPON)
AddEventHandler("vorpinventory:removeammo", INVENTORY_API.MAIN.CLEAR_GUNBELT_AMMO)
AddEventHandler("vorpCore:getItemContainingMetadata", INVENTORY_API.MAIN.GET_ITEM_CONTAINING_METADATA)
AddEventHandler("vorpCore:getItemMatchingMetadata", INVENTORY_API.MAIN.GET_ITEM_MATCHING_METADATA)
AddEventHandler("vorpCore:getItemCount", INVENTORY_API.MAIN.GET_ITEM_COUNT)
AddEventHandler("vorpCore:getUserInventory", INVENTORY_API.MAIN.GET_INVENTORY)
AddEventHandler("vorpCore:canCarryItems", INVENTORY_API.MAIN.CAN_CARRY_ITEM_AMOUNT) -- deprecated
AddEventHandler("vorpCore:canCarryItem", INVENTORY_API.MAIN.CAN_CARRY_ITEM)
AddEventHandler("vorpCore:canCarryWeapons", INVENTORY_API.MAIN.CAN_CARRY_WEAPON)
AddEventHandler("vorpCore:subBullets", INVENTORY_API.MAIN.REMOVE_WEAPON_BULLETS)
AddEventHandler("vorpCore:addBullets", INVENTORY_API.MAIN.ADD_AMMO_TO_GUNBELT)
AddEventHandler("vorpCore:getWeaponBullets", INVENTORY_API.MAIN.GET_WEAPON_BULLETS)
AddEventHandler("vorpCore:getUserWeapons", INVENTORY_API.MAIN.GET_WEAPONS)
AddEventHandler("vorpCore:getUserWeapon", INVENTORY_API.MAIN.GET_WEAPON_BY_ID)
AddEventHandler("vorpCore:registerUsableItem", INVENTORY_API.MAIN.REGISTER_ITEM)
AddEventHandler("vorpCore:registerInventory", INVENTORY_API.SECONDARY.REGISTER)
AddEventHandler("vorpCore:removeInventory", INVENTORY_API.SECONDARY.REMOVE)
AddEventHandler("vorpCore:openCustomInventory", INVENTORY_API.OPEN_INVENTORY)   -- main or secondary
AddEventHandler("vorpCore:closeCustomInventory", INVENTORY_API.CLOSE_INVENTORY) -- main or secondary
AddEventHandler("vorpCore:setInventoryItemLimit", INVENTORY_API.SECONDARY.SET_ITEM_LIMIT)
AddEventHandler("vorp_inventory:Server:AddPermissionMoveToCustom", INVENTORY_API.SECONDARY.ADD_PERMISSION_MOVE_TO)
AddEventHandler("vorp_inventory:Server:AddPermissionTakeFromCustom", INVENTORY_API.SECONDARY.ADD_PERMISSION_TAKE_FROM)
AddEventHandler("vorp_inventory:Server:BlackListCustom", INVENTORY_API.SECONDARY.BLACKLIST)
AddEventHandler("vorpCore:setInventoryWeaponLimit", INVENTORY_API.SECONDARY.SET_WEAPON_LIMIT)
AddEventHandler("vorp_inventory:Server:updateCustomInventorySlots", INVENTORY_API.SECONDARY.UPDATE_SLOTS)
